### PR TITLE
Remove Best Practices merged into spec

### PR DESCRIPTION
**Pull request by Sergiodero**
**Best Practice Proposal:**

Referenced from issue #57 

A [recently implemented proposal](https://github.com/google/transit/pull/386) has merged specific best practices directly into the GTFS specification. This merge included content from the following files under the Practice Recommendations Organized by File section:

- agency.txt
- routes.txt
- stop_times.txt
- fare_attributes.txt
- shapes.txt
- feed_info.txt

This proposal removes the duplicated content from the Best Practices document, to avoid duplicity and consolidating a single source of truth.

### CODE REVIEW

**Comment by Sergiodero** [comment]
As this PR has been open for more than a week, I'm calling a vote as per the process outlined in the [GTFS Schedule Best Practices Amendment Process](https://github.com/MobilityData/GTFS_Schedule_Best-Practices/blob/master/README.md#gtfs-schedule-best-practices-amendment-process). 

This vote is for the removal of best practices [content that have migrated over to the GTFS spec](https://github.com/google/transit/pull/386). 

Voting ends on 2023-08-29 at 23:59:59 UTC.

Thanks

**Comment by markstos** [comment]
+1 RideAmigos

**Comment by skinkie** [comment]
+1 OpenGeo

**Comment by bdferris-v2** [comment]
+1 Google

**Comment by Sergiodero** [comment]
The vote ended on 2023-08-29 at 23:59:59 UTC. This PR passes with 3 votes in favor (from RideAmigos, OpenGeo & Google) and 0 opposed!

Thanks to everyone who participated!

**Review by isabelle-dr — APPROVED** [review]
Hello Sergio! 
I cross-checked this PR with the spec. Everything is covered. 

Thank you for working on this, ready to merge :)

**Pull request merged**
