### PR TITLE
Make `bikes_allowed` a recommended field for all travel modes.

### PR DESCRIPTION
**Pull request by bdferris-v2**
**Best Practice Proposal:**

PR #55 recently made `trips.txt bikes_allowed` a recommended field for ferry routes.  This PR proposes to expand that recommendation to all travel modes.

**Use Cases:** 

As discussed in PR #55, for multi-modal journeys involving bike + public transit, whether a particular vehicle allows bikes on board or not can lead to significantly different routing results, especially for vehicles that cross water (e.g. ferries, trains/metros with a dedicated bridge or tunnel) or have other dedicated right-of-way.

More generally, it's useful to riders to know if bikes are allowed on transit vehicles, even if there is a comparable biking route that could be used as a fallback.  For cyclists who are looking for a transit leg to make their overall ride shorter, an all-bike alternative might not be much of a fallback.

For all these reasons, it is recommended that data providers be explicit about whether bikes are allowed on their vehicles or not, regardless of route type.

**Data Examples:**

In the text, we try to be clear that data providers should be explicit about whether bikes are allowed (`bikes_allowed=1`) or disallowed (`bikes_allowed=2`).  It's not enough to specify `bikes_allowed=0`, since that is the same as unknown.  That said, we do acknowledge that some providers don't know in advance if bikes are allowed.

### CODE REVIEW

**Comment by bdferris-v2** [comment]
It's been over a week since opening the proposal, so I'm going to open the vote to see where we stand.

I'd like to call for votes starting now and lasting 7 full calendar days until Thursday June 28 23:59:59 UTC.

**Comment by emmambd** [comment]
The vote ended on 2023-06-28 at 23:59:59 UTC. This PR fails with 0 votes. 

Curious to hear thoughts from #55 participants: @dekarl, @e-lo, @derhuerst and @themightychris.

**Comment by derhuerst** [comment]
+1

**Comment by dekarl** [comment]
+1

I was trying to word the suggestion in a specific way that describes an easy to implement automated test to help directing effort into high value improvements. That may have been a bit tunnel visioned (is that a word?) for my application.

The generic wording is good, too. It better fits the overall style of the document.

**Comment by dekarl** [comment]
I noticed that it's now possible to mark a field as recommended in the GTFS spec itself. (see https://github.com/google/transit/pull/386/commits/2114050b07e458b679d0029d5f4552f00e43fc44 via https://github.com/MobilityData/GTFS_Schedule_Best-Practices/issues/57 )

I think this is a good fit. I also recognized many of your names over there. Thank you for picking up and moving forward with recommended fields.

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this PR will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.

**Pull request closed without merging**
