### PR TITLE
Add timepoint best practice back

### PR DESCRIPTION
**Pull request by isabelle-dr**
Another accidental removal in #44: timepoint should be provided. 
This is not something covered by the spec. 

We have a validator rule that is based on this best practic: [missing_timepoint_column](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#missing_timepoint_column).

I've added back the statement as-is.

### CODE REVIEW

**Comment by bdferris-v2** [comment]
Seems reasonable to me.

**Comment by isabelle-dr** [comment]
This PR has been open for more than a week, I am going to call a vote. 
Voting ends on 2023-04-12 at 23:59:59 UTC.

Thanks

**Comment by derhuerst** [comment]
👍, both from the perspective of my personal projects as well as [bbnavi](https://bbnavi.de)'s.

**Comment by bdferris-v2** [comment]
+1 from Google

**Review by tzujenchanmbd — APPROVED** [review]
Looks great to me!

**Pull request merged**
