### PR TITLE
suggest explicit bikes_allowed for ferry trips to avoid big detours

### PR DESCRIPTION
**Pull request by dekarl**
**Best Practice Proposal:**

Ferry trips should be explicit about bikes being allowed or not. Contrary to buses avoiding ferries in a multi-modal router due to missing data leads to big detours for cyclists.

**Use Cases:** 

Taking the bus to the ferry in Nierstein, then walking the last 2 miles "only" takes an hour.
image

When considering taking your bike the ferry is avoided due to missing data, leading to a big detour via the next bridge.
image

### CODE REVIEW

**Comment by dekarl** [comment]
It's been two weeks since opening the proposal with only positive reactions.

I'd like to call for votes starting now and lasting two weeks until Thursday June 8st 23:59:59 UTC

**Comment by bdferris-v2** [comment]
To play devil's advocate: I can think of situations where not knowing the bike facilities for a particular transit leg could still lead to big detours, regardless of mode.  I think the best practice would rather be: "Please specify `bikes_allowed` if you can".  But that's generally a best practice for all fields, yeah?  If you have information (bike facilities, wheelchair accessibility, etc), you should generally add it to a feed where you can.

**Comment by dekarl** [comment]
> To play devil's advocate: I can think of situations where not knowing the bike facilities for a particular transit leg could still lead to big detours, regardless of mode. I think the best practice would rather be: "Please specify `bikes_allowed` if you can". But that's generally a best practice for all fields, yeah? If you have information (bike facilities, wheelchair accessibility, etc), you should generally add it to a feed where you can.

I agree. Specifying optional data is always better. The idea behind the restriction to ferries is the high likelyhood of big detours, while for the majority of trips there is no big detour.

So "is it a ferry" is a very simple test to direct improvements towards high rewards.

**Comment by e-lo** [comment]
>But that's generally a best practice for all fields, yeah? 

The difference in having it as a best practice is that it will (hopefully) eventually make its way to the validator so that if you have a ferry mode without explicit bikes allowed, it will warn you and let you know that this could lead to unnecessarily long detours.

I guess this brings up the general prioritization of the spec between `MAY`, `SHOULD`, and `SHALL` and what is the threshold of things we should elevate from `MAY` to `SHOULD`.  

My 2-cents:

1. Things that cause ambiguity in how gtfs-consumers should interpret the data
2. Things that could severely diminish the transit customer experience (which I think this item meets the threshold for)

**Comment by e-lo** [comment]
+1 UrbanLabs

**Comment by dekarl** [comment]
> > But that's generally a best practice for all fields, yeah?
> 
> The difference in having it as a best practice is that it will (hopefully) eventually make its way to the validator so that if you have a ferry mode without explicit bikes allowed, it will warn you and let you know that this could lead to unnecessarily long detours.

That is where I'm coming from. I was actually sent here after asking what validator was in active use and easy to extend for such suggestions towards our data providers in Germany. "That sounds like a good rule for a validator. Is this already a best practice? That makes it easier to add an new validation and have it enabled by default."

I plan to add it to [gtfsvtor](https://github.com/mecatran/gtfsvtor). I have not yet looked at [gtfs-validator](https://github.com/MobilityData/gtfs-validator).

**Comment by bdferris-v2** [comment]
To restate my main argument, I think bike routing can be impacted whenever you have a transit leg over water, whether it be a ferry or a rail line over a dedicated bridge.  So I'm mainly advocating that `bikes_allowed` be marked as "Should be included", regardless of mode.  And indeed, that would let us add a @Recommended annotation for the field in the [GTFS Validator](https://github.com/MobilityData/gtfs-validator).  Put another way, why limit ourselves to just ferries here?

**Comment by themightychris** [comment]
+1 Jarvus

**Review by emmambd — APPROVED** [review]
The vote ended on 2023-06-08 at 23:59:59 UTC. This PR passes with 3 votes in favor. 

If anyone would like to act on the discussion here and expand the new best practice to include any transit leg over water instead of just ferries, please open a new PR.

**Comment by bdferris-v2** [comment]
Regarding `bikes_allowed` for all travel modes, I opened PR #56 to see see if we have enough consensus to expand the best practice.

**Pull request merged**
