### PR TITLE
fix: make recommendation consistent across agency.txt, routes.txt, fare_attributes.txt

### PR DESCRIPTION
**Pull request by briandonahue**
### Context

Addressing some inconsistencies in best practice recommendations and validation rules, including #52, [#878](https://github.com/MobilityData/gtfs-validator/issues/878)

### Proposed Change

Update language for `agency.txt`, `routes.txt`, and `fare_attributes.txt` to recommend `agency_id` to be included even if there is only one agency in the feed.  

### Question

Would it be useful to also mention that it is required when there is more than one agency, and link to the spec (e.g. [`agency.txt`](https://gtfs.org/schedule/reference/#agencytxt)) or is it enough to mention the best practice for single agencies here?

### CODE REVIEW

**Review by isabelle-dr — APPROVED** [review]
**Additional context about this PR:**
https://github.com/MobilityData/GTFS_Schedule_Best-Practices/pull/44 was intended to remove Best Practices already covered by the spec. The Best Practice around agency_id in routes.txt was removed but wasn't "already covered by the spec":

| agency_id | Must be included if it is defined in agency.txt. |

We are happy with the change, @briandonahue as per the[ Amendment Process](https://github.com/MobilityData/GTFS_Schedule_Best-Practices#gtfs-schedule-best-practices-amendment-process) for this repo, the next steps are:
- wait until this PR has been open for 7 days to leave time for people to comment
- open a vote ([here](https://github.com/MobilityData/GTFS_Schedule_Best-Practices/pull/44#issuecomment-1009389423) is an example)
- the proposal is accepted if there are at least 3 votes with at least 80% in favor

**Comment by briandonahue** [comment]
I would like to call for a vote in accordance with the [Amendment Process](https://github.com/MobilityData/GTFS_Schedule_Best-Practices#gtfs-schedule-best-practices-amendment-process) for updating the language to be more consistent in the recommendation that `agency_id` always be included in `agency.txt`, `routes.txt`, and `fare_attributes.txt` even if there is only one agency in the feed.  

Voting ends on 2023-02-13 at 23:59:59 UTC.

**Comment by e-lo** [comment]
+1

**Comment by spellegrom** [comment]
+1

**Comment by timMillet** [comment]
+1 (Transit)

**Comment by jfabi** [comment]
+1 from the MBTA

**Comment by briandonahue** [comment]
The vote ended on 2022-02-13 at 23:59:59 UTC. This PR passes with at least 3 votes in favour and 0 opposed.

Thanks to all involved!

**Comment by isabelle-dr** [comment]
Great, thanks, everyone!

**Pull request merged**
